title: Alexander Groeger CV
profile_img: /assets/img/profile.jpg
icon_img: /assets/img/icon.png

name: "Alexander Groeger"
job: "〈Data Engineer〉"

phone_number: 513-658-1152
address: Oregonia, Ohio
email: alex.h.groeger@gmail.com
linkedin_username: alexander-h-groeger
github_username: AlexanderGroeger
instagram_username: 
twitter_username: 
facebook_username: 
youtube_username: 
blog_url: 

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:
url: "https://alexander-groeger.github.io"

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag